# Generated by Django 2.2.1 on 2019-05-08 23:09

from django.db import migrations
import internationalflavor.iban.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iban',
            field=internationalflavor.iban.models.IBANField(),
        ),
    ]
